// Exercise publication-dependent decisions without a browser or network.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'dist/app.js'),'utf8').split('load().catch(')[0];
const ctx=vm.createContext({Intl,Date,Number,console});vm.runInContext(source,ctx);
const research=JSON.parse(fs.readFileSync(path.join(root,'dist/data/research-latest.json')));
const market=JSON.parse(fs.readFileSync(path.join(root,'dist/data/market-latest.json')));
vm.runInContext('research='+JSON.stringify(research)+';market='+JSON.stringify(market),ctx);
assert.equal(vm.runInContext('contractFor("ADSK")',ctx),null,'Historical chain cannot be contract-ready');
const base={ticker:'ADSK',classification:'eligible',verified:true,quoteObservedAt:new Date().toISOString(),strike:200,delta:.65,bid:98,ask:100,openInterest:3000,iv:.3,expiration:`${new Date().getUTCFullYear()+2}-01-21`,fundamentalTargets:{bear:260,base:300}};
const select=contracts=>{vm.runInContext('market.contractProfiles='+JSON.stringify(contracts),ctx);return vm.runInContext('contractFor("ADSK")',ctx);};
assert.ok(select([base]),'Contract above $6,500 is allowed when quality passes');
for(const updates of [{verified:false},{expiration:'2025-01-17'},{quoteObservedAt:'2026-01-01T00:00:00Z'},{delta:.8},{bid:80},{openInterest:-1},{iv:0},{strike:300}])assert.equal(select([{...base,...updates}]),null);
assert.equal(select([{...base,reference:'lower OI',openInterest:2000,bid:99},{...base,reference:'highest OI'}]).reference,'highest OI');
assert.equal(select([{...base,reference:'wider'},{...base,reference:'tighter',bid:99}]).reference,'tighter');
vm.runInContext('activeFilter="tier3"',ctx);
assert.deepEqual(research.candidates.filter(c=>vm.runInContext('matchesFilter('+JSON.stringify(c)+')',ctx)).map(c=>c.rank),[8,9,10,11]);
const company=research.candidates[0];
company.earningsSurprises=[{epsBasis:'unknown',epsConsensus:1,epsResult:'BEAT'}];
const html=vm.runInContext('earningsQuality('+JSON.stringify(company)+')',ctx);
assert.ok(html.includes('Net income')&&html.includes('UNVERIFIED'));
assert.ok(!html.includes('>BEAT<'),'Unverifiable basis cannot display an EPS beat');
assert.equal(vm.runInContext('supportAlertTarget("$390–396")',ctx),396,'Support alert uses the upper edge of the zone');
assert.equal(vm.runInContext('supportTiming({price:224.5,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160"}).state',ctx),'in','CRM at first support must be recognized from price geometry');
assert.equal(vm.runInContext('entryTimingStatus({price:224.5,todayPct:-0.2,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",action:"WAIT FOR REVERSAL",thesisStatus:"INTACT"}).label',ctx),'BUY ZONE — ENTRY 1','First support is a staged entry at any day change');
assert.equal(vm.runInContext('entryTimingStatus({price:200,todayPct:1,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",thesisStatus:"INTACT"}).label',ctx),'ADD ZONE — ADD 2','Second support is the next averaging stage');
assert.equal(vm.runInContext('entryTimingStatus({price:157,todayPct:-7,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",thesisStatus:"INTACT"}).label',ctx),'ADD ZONE — FINAL ADD','Final support remains a stage even after a sharp fall');
assert.equal(vm.runInContext('entryTimingStatus({price:224.5,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",thesisStatus:"BROKEN"}).label',ctx),'THESIS CHECK — WAIT','Broken thesis blocks support averaging');
assert.equal(vm.runInContext('entryTimingStatus({price:225.2,todayPct:-3,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",action:"WAIT FOR REVERSAL",thesisStatus:"INTACT"}).label',ctx),'NEAR SUPPORT — WATCH','Near support is not an entry');
assert.equal(vm.runInContext('nextRobinhoodAlert({price:414.46,entry1:"$390–396",add2:"$378–384",finalAdd:"$345–355"}).target',ctx),396,'Next alert should be first uncrossed support');
assert.equal(vm.runInContext('nextRobinhoodAlert({price:227.6,entry1:"$234–238",add2:"$223–228",finalAdd:"$209–213"}).target',ctx),213,'Already-crossed/in-zone supports must advance to the next lower alert');
assert.equal(vm.runInContext('stageAction({price:225.2,entry1:"$221–225",add2:"$198–203",finalAdd:"$154–160",action:"WAIT FOR REVERSAL",thesisStatus:"INTACT"})',ctx),'NEAR SUPPORT — WATCH','Legacy action wording must not override current geometric support state');
assert.ok(!vm.runInContext('supportEvidence("$221–225 supports price. The stock is already testing this zone, so a hold/reclaim is required.")',ctx).includes('required'),'Legacy reversal advice is removed from current support evidence');
assert.equal(vm.runInContext('attentionRows(research.candidates.filter(c=>c.qualified)).every(x=>x.s.state==="in"||x.s.state==="near")',ctx),true,'Attention rows contain only stocks at or near current supports');
const previousMarket=JSON.parse(JSON.stringify(market));
const previousResearch=JSON.parse(JSON.stringify(research));
previousMarket.candidatePlans.find(p=>p.ticker==='CRM').entry1='$215–219';
previousResearch.candidates.find(c=>c.ticker==='CRM').score-=1;
vm.runInContext('previousMarket='+JSON.stringify(previousMarket)+';previousResearch='+JSON.stringify(previousResearch),ctx);
const changes=vm.runInContext('publishedChanges()',ctx);
assert.ok(changes.some(x=>x.ticker==='CRM'&&x.detail.includes('1st support $215–219 → $221–225')),'Saved support revision is visible');
assert.ok(changes.some(x=>x.ticker==='CRM'&&x.detail.includes('Research score')),'Saved research score revision is visible');
assert.equal(vm.runInContext('research.candidates.filter(c=>c.qualified).filter(c=>planFor(c.ticker)).length',ctx),research.candidates.filter(c=>c.qualified).length,'Every qualified ticker must have a market plan');
const currentIV=vm.runInContext('contractCard('+JSON.stringify(base)+',true)',ctx);
assert.ok(currentIV.includes('Implied volatility <span>reported</span>')&&currentIV.includes('30.0%'));
const modeled=vm.runInContext('contractCard('+JSON.stringify({...base,iv:null,modeledIV:.43})+',true)',ctx);
assert.ok(modeled.includes('Implied volatility <span>modeled</span>')&&modeled.includes('~43.0%'));
const reported=vm.runInContext('documentedReviewCount({candidates:[{qualified:true}],rejected:[{ticker:"OLD"}],researchFunnel:{deepReviewCount:47}})',ctx);
assert.equal(reported.documented,2,'Only listed reviewed outcomes count');
assert.equal(reported.unreconciled,true,'Historical deep-review pool mismatch requires prominent warning');
const consistent=vm.runInContext('documentedReviewCount({candidates:[{qualified:true}],rejected:[{ticker:"OLD"}],researchFunnel:{deepReviewCount:2}})',ctx);
assert.equal(consistent.unreconciled,false,'Reconciled daily scans must not display a false warning');
console.log('Desk integrity passed: permanent ranks, filters, comparable earnings, Robinhood alert targets, current/modeled IV, no cost cap, OI/spread ranking, and eligibility boundaries.');

