from pathlib import Path
R=Path(__file__).resolve().parents[1];D=R/'dist'
p=D/'app.js';s=p.read_text()
s=s.replace("selected='RDDT'","selected='ADSK'")
s=s.replace("'cards/top-15-research-2026-10-07.png'","'cards/strict-watchlist-2026-10-07.png'")
s=s.replace("'Top 15 research stocks'","'Full strict LEAPS watchlist'").replace("'Share top 15 image'","'Share full list image'")
s=s.replace("!scan.shortlist.includes(ticker)","!scan.candidates.some(r=>r.ticker===ticker)")
s=s.replace("new Date(meta[key])","new Date(meta[key]??'')")
start=s.index('function render(){');end=s.index('\nfunction choose(',start)
new=r'''function render(){
 document.querySelectorAll('[data-group]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.group===group)));
 document.getElementById('candidates-panel').setAttribute('aria-labelledby',group+'-tab');
 document.getElementById('group-note').textContent=group==='shortlist'?'7 audited company candidates. Tier 1 = research first; Tier 2 = stated exceptions. Live option quality is unverified.':'Early watch: IOT has improving results but fails our valuation/stock-compensation quality filter. It is not in the qualified list.';
 document.getElementById('rows').innerHTML=members().map(r=>`<tr data-ticker="${safe(r.ticker)}" class="${r.ticker===selected?'selected-row':''}"><td><button class="company-button" data-ticker="${safe(r.ticker)}" aria-label="View ${safe(r.company)}" aria-pressed="${r.ticker===selected}"><strong><i>${String(r.rank).padStart(2,'0')}</i>${safe(r.ticker)}</strong><small>Tier ${r.tier} · ${r.score}/100</small></button></td><td class="positive">+${r.quarter.revg[0].toFixed(1)}%</td><td class="drawdown">−${pct(r.drawdown)}</td><td>${money.format(r.price)}</td></tr>`).join('');
 const r=scan.candidates.find(r=>r.ticker===selected),q=r.quarter,m=r.technical;
 const actions=`<div class="image-actions"><button type="button" class="share-image" data-share-image="${safe(r.ticker)}" aria-describedby="share-status">Share this stock</button><a href="${cardPath(r.ticker)}" download>Download PNG</a></div><p id="share-status" class="share-help" role="status">On iPhone, choose Save Image in the share menu.</p>`;
 const quarters=`<h3>Last 4 quarters · same-quarter YoY</h3><p class="small">Revenue and net income compare the same fiscal quarter a year earlier. Swipe the table for GAAP EPS.</p><div class="quarter-scroll"><table class="quarter-table"><thead><tr><th>Fiscal quarter</th><th>Rev. YoY</th><th>GAAP NI / prior ($M)</th><th>NI YoY</th><th>GAAP EPS</th></tr></thead><tbody>${[3,2,1,0].map(i=>`<tr><td>${safe(q.periods[i])}</td><td>+${q.revg[i].toFixed(1)}%</td><td>${q.net[i].toFixed(1)} / ${q.net[i+4].toFixed(1)}</td><td>${q.nyoy[i]===null?'Loss → profit':q.nyoy[i].toFixed(1)+'%'}</td><td>$${q.eps[i].toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`;
 const sections=[['Why the stock is down',r.down],['Free cash flow',r.cash],['Margin trend',r.margins],['Balance sheet / dilution',r.balance],['Competitive moat',r.moat],['Valuation assessment',r.valuation],['Technical condition',`${r.state}: 50-day SMA $${m.sma50.toFixed(2)}; 200-day SMA $${m.sma200.toFixed(2)}. Observed 20-session low $${m.low20.toFixed(2)} / 60-session low $${m.low60.toFixed(2)}. Support is not guaranteed. 20-session return ${(m.return20*100).toFixed(1)}% versus SPY +1.7%.`],['Prior-high recovery',`Mechanical stock upside +${(r.upsideToHigh*100).toFixed(1)}% to $${r.high.toFixed(2)} ${r.basis} reference. ${r.recovery}`],['Biggest risk',r.risk],['What invalidates the thesis',r.invalidation],['LEAP suitability',`${r.leapQuality}. ${r.optionNote}`]];
 document.getElementById('detail').innerHTML=`<div class="detail-head"><div><h2>${safe(r.ticker)} <small>${money.format(r.price)}</small></h2><p>${safe(r.company)}</p></div><span class="badge ${r.qualified?'':'exception'}">TIER ${r.tier} · ${r.qualified?'QUALIFIED COMPANY':'EARLY WATCH'}</span></div><div class="metrics"><div><span>Research score</span><strong>${r.score}/100</strong></div><div><span>Off ${safe(r.basis)} high</span><strong class="drawdown">−${pct(r.drawdown)}</strong></div><div><span>GAAP NI growth</span><strong class="positive">${q.improvingQuarters}/4 quarters</strong></div></div><div class="detail-copy">${actions}<div class="quality">${safe(r.qualified?'Passes the company screen; stated exceptions below. No option contract verified.':'Not qualified: excessive valuation and stock compensation outweigh otherwise improving results.')}</div>${quarters}<h3>Specific catalysts / AI monetization</h3><ul class="catalysts">${r.catalysts.map(x=>`<li>${safe(x)}</li>`).join('')}</ul>${sections.map(([title,value])=>`<h3>${safe(title)}</h3><p>${safe(value)}</p>`).join('')}<h3>Score breakdown</h3><p class="small">${Object.entries(r.scoreBreakdown).map(([k,v])=>`${safe(k)} ${v}/${r.scoreMaximums[k]}`).join(' · ')}</p><p class="small">Scores, technical labels, risk grades, catalysts and recovery assessments are research judgments. Prices and GAAP figures are reported data.</p><div class="sources">${r.sources.map(x=>`<a href="${safe(x.url)}" target="_blank" rel="noopener">${safe(x.label)}</a>`).join('')}<a href="reports/strict-leaps-2026-10-07.html#${r.ticker}">Full report</a></div></div>`;
 prepareCard(r.ticker);
 document.getElementById('rejected-list').innerHTML=scan.rejected.map(x=>`<li><strong>${safe(x.ticker)}</strong> — ${safe(x.reason)} <a href="${safe(x.url)}" target="_blank" rel="noopener">Source</a></li>`).join('');
 document.getElementById('rankings').innerHTML=Object.entries(scan.rankings).map(([k,v])=>`<p><strong>${safe({bestOverall:'Best overall LEAP research',highestBounce:'Highest conditional bounce potential',safestQuality:'Safest high-quality businesses'}[k])}</strong><br>${v.map((t,i)=>`${i+1}. ${t}`).join(' · ')}</p>`).join('');
}'''
s=s[:start]+new+s[end:]
s=s.replace("fetch('data/scan-2026-10-07.json')","fetch('data/strict-scan-2026-10-07.json',{cache:'no-store'})")
p.write_text(s)
p=D/'index.html';s=p.read_text().replace('20261007-top15-share','20261007-strict-v1')
s=s.replace('Profitable companies, improving earnings and a 30–70% drawdown.','A strict GAAP audit: 7 company candidates + 1 early watch. Live option chains unverified.')
s=s.replace('Save the top 15 as one image','Save the full strict list as one image').replace('8 shortlist candidates + 7 additional watchlist stocks','7 qualified company candidates + 1 early valuation watch · no padding')
s=s.replace('cards/top-15-research-2026-10-07.png','cards/strict-watchlist-2026-10-07.png')
s=s.replace('Includes growth, drawdowns, catalysts and the dated upload.','Includes scores, tiers, growth, drawdowns and exact scan time.')
s=s.replace('October 7, 2026</strong>','Oct 7, 2026 · 2:11:33 AM CDT</strong>').replace('Exact completion time not recorded','Exact completion time · Central Time')
s=s.replace('datetime="2026-10-07T06:11:24.061314Z">Oct 7, 2026 · 1:11:24 AM CDT','>Publication timestamp loading')
s=s.replace('<strong>08</strong><span>Research shortlist','<strong>07</strong><span>Qualified companies').replace('<strong>36</strong><span>Companies reviewed','<strong>01</strong><span>Early valuation watch').replace('<strong>3–4</strong><span>Improving quarters · shortlist','<strong>04</strong><span>GAAP profits · all candidates').replace('<strong>2028–29</strong><span>Expirations to investigate','<strong>0/5</strong><span>Option points · unverified')
s=s.replace('Shortlist <span>8</span>','Qualified <span>7</span>').replace('Broader list <span>28</span>','Early watch <span>1</span>')
s=s.replace('Ranked by AI opportunity and earnings consistency. Option liquidity still needs checking.','Tier 1 = research first. Tier 2 = stated exceptions. Live option quality unverified.')
s=s.replace('Rev. YoY</th>','Latest rev.</th>')
s=s.replace('href="data/scan-2026-10-07.json"','href="data/strict-scan-2026-10-07.json"')
s=s.replace('<a href="LEAPS_Stock_Watchlist_2026-10-07.xlsx" download>Full workbook</a>','<a href="reports/strict-leaps-2026-10-07.html">Full audited report</a><a href="data/strict-scan-2026-10-07.csv" download>Scan CSV</a>')
start=s.index('<section class="method">');end=s.index('<footer>',start)
s=s[:start]+'''<section class="method"><div><p class="eyebrow">STRICT SCREEN</p><h2>Evidence before an option contract.</h2></div><div><p><strong>Tier 1:</strong> Autodesk, Reddit, Adobe. Research first, with disclosed risks. <strong>Tier 2:</strong> Accenture, Intuit, Salesforce, HubSpot. Profitable businesses with cash-flow, margin, growth or leverage exceptions.</p><p><strong>Tier 3:</strong> Samsara is an early watch excluded from the qualified list because valuation and stock compensation are too demanding.</p><p><strong>Scoring:</strong> 25 fundamentals + 20 earnings + 15 valuation + 15 catalysts + 10 moat + 5 macro + 5 technicals + 5 options. All receive zero option points because live IV, open interest, delta and spreads could not be verified.</p><p><strong>High reference:</strong> use the stated 52-week high or older ATH. ADSK's ATH is from 2021; CRM from 2024; IOT from 2025. They are not all 30% below their recent 52-week highs. Mechanical recovery upside is not a forecast.</p><p><strong>LEAPS:</strong> verify listed 18–30 month expirations and ~0.70–0.85 delta ITM calls. Check spread, IV, open interest, break-even and post-earnings volatility before choosing a contract. Entire option premium is at risk.</p><p><strong>Coverage:</strong> targeted audited research, not an exhaustive automatic market-wide scan. Financial comparisons use the same fiscal quarter YoY; primary statements resolve source conflicts.</p></div></section><section class="method"><div><h2>Final rankings</h2></div><div id="rankings"></div></section><section class="rejections"><details><summary>12 rejected / not selected — exact reasons</summary><ul id="rejected-list"></ul></details></section>'''+s[end:]
s=s.replace('Download all 8 image cards','Download all 8 fresh image cards')
s=s.replace('href="cards/candidate-cards.zip"','href="cards/strict-candidate-cards.zip"')
p.write_text(s)
p=D/'styles.css';s=p.read_text()+'''\n.quarter-scroll{overflow-x:auto;margin:14px 0 24px;max-width:100%;border:1px solid var(--line);border-radius:7px}.quarter-table{min-width:690px;table-layout:auto}.quarter-table th,.quarter-table td{display:table-cell!important;width:auto!important;padding:12px!important;font-size:.8rem;white-space:nowrap}.quarter-table th:first-child,.quarter-table td:first-child{text-align:left}.quarter-table thead{position:static}.catalysts{padding-left:20px;color:#c7d1d5;line-height:1.6}.catalysts li+li{margin-top:8px}.detail-head h2 small{font-size:1rem;color:var(--muted)}.sources{margin-top:20px}.full-report{max-width:1080px;font-size:1rem;line-height:1.65}.full-report article{border-top:1px solid var(--line);margin-top:32px;padding-top:24px}.full-report h3{color:var(--gold);margin:22px 0 8px;font-size:1rem}.full-report p{color:#c7d1d5}.full-report h2{line-height:1.35}.rejections{margin-top:28px;border:1px solid var(--line);border-radius:8px;padding:16px 20px}.rejections summary{cursor:pointer;min-height:44px;line-height:1.6}.rejections li{line-height:1.6;margin-bottom:16px;color:var(--muted)}@media(max-width:760px){.full-report{padding:20px 14px}.full-report h2{font-size:1.35rem}.quarter-scroll{margin:12px 0 20px}.rejections{padding:14px}.full-report .sources a{min-height:44px;display:inline-flex;align-items:center}}\n''';p.write_text(s)
print('Updated strict scan dashboard, mobile quarterly evidence, rankings and share links.')
